### ISSUE TITLE
Group-Project-Kanban-Board-Set-up

### ISSUE THREAD

**Issue by Alusp** [Suzi216/space-X#25]
### Below is the link of our Project:
[Project-Link](https://github.com/Suzi216/Space-X/projects/1)

**Comment by prolajumokeoni** [comment]
Hi @Alusp and @Suzi216 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Good Kanban board setup



## Required Changes ♻️

- [ ] Based on the [requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/group-project/setup_kanban_board.md#project-requirements), `Decide who will be the assignee for the cards marked as group tasks` All cards on your Kanban board should have assignees.

_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by medaminedev66** [comment]
Hi @Alusp and @Suzi216 😃, 

Your project is complete! Wishing you all the best with the capstone project 🦅
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
